name: Main

on:
  workflow_dispatch:
  push:
    branches: ["main", "releases"]
    paths:
      - "modern_python_project_template/**"
      - "**.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "modern_python_project_template/**"
      - "**.toml"

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: "./.github/actions/environment"

      - name: Running pytest
        run: poetry run pytest
