name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: "./.github/actions/environment"

      - name: Ruff check
        run: poetry run ruff check

      - name: Pytest
        run: poetry run pytest

      - name: Build Python WHL package
        run: poetry build -f wheel

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./dist/*.whl
          file_glob: true
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post message to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C04KXAF6CKB"
          slack-message: "GitHub release:\n${{ github.ref }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

